### ISSUE TITLE
Update Keycloak libs after updating keycloak depoyment because of security alert

### ISSUE THREAD

**Issue by sippsack** [dukecon/doag-user-spi#1]
https://github.com/dukecon/doag-user-spi/network/alert/pom.xml/org.keycloak:keycloak-core/open

**Comment by dasniko** [comment]
Wrong repository, this is just the spi, not the KC deployment.
The SPI must not use a newer version of the deps than the running KC instance.
@ascheman is already aware of, I talked to him.

**Comment by sippsack** [comment]
I thought we also need to replace keycloak lib after updating keycloak. I need to change the title.

**Comment by srose** [comment]
Done?
